### PR TITLE
Bump to clojure 1.9 & clj-http 3.9.0

### PR DESCRIPTION
**Pull request by rborer**
So we use the latest available libraries :-)

### CODE REVIEW

**Comment by jjl** [comment]
Merged. We don't currently have a release manager, however, so don't expect it to make it to clojars just yet. I don't suppose I could persuade you to take the job? :)

**Comment by rborer** [comment]
@jjl Thanks. I was indeed going to ask how to make it to clojars :-)

I would love to help maintaining this great library! Besides checking issues & pull requests, what do you expect from a release manager?

**Comment by jjl** [comment]
Paging @kentfredric, who was a better release manager than I will ever be :)

Basically, it's mostly about updating the release notes and trying to ensure we don't push something bad out by mistake. Kent had his own processes for this which he brought from the perl world (where I knew him from before).

Irresponsible is a voluntary organisation and so we try not to put too great a burden on volunteers. At the minute, the library has noone maintaining it, so even mediocre release management would be an improvement :)

**Comment by jjl** [comment]
You *should* have an invite to join the org waiting for you which should resolve everything github-side. I'll figure out what I need to do with clojars

**Comment by rborer** [comment]
Thanks, I'm in on github 😄 .

For clojars, you need to add me as a member into the [irresponsible group](https://clojars.org/groups/irresponsible/). My username there is the same than on github.

@kentfredric let me know if you have any release management guidelines I should follow, otherwise I have my own ones (which includes not pushing broken stuff 😉 ).

**Comment by jjl** [comment]
Oh, and for this particular module, I used to check against the old repo, since I never found anyone with sufficient privileges on it to e.g. add a link at the top of the README and people keep filing issues against it. Probably because it's still listed as the correct url on toolbox

**Comment by rborer** [comment]
Have we tried to reach to github directly to ask for write permissions to the original repo?

Also, you're talking about Slack, are you referring to [clojurians](http://clojurians.net/) slack workspace or another one?

**Comment by jjl** [comment]
We did ask github, but their procedures allow only for us to transfer *all* his repos to another user (we have no real knowledge of what half of them are!) and only with the cooperation of his family (who we'd obviously rather not bother).

Yes, I meant the clojurians slack. I don't think there's another with any real number of clojure users?

**Comment by jjl** [comment]
You should now be a member of the irresponsible group on clojars.

**Comment by rborer** [comment]
[Release 0.6.2 is out](https://github.com/irresponsible/tentacles/releases/tag/0.6.2) :-)

So far so good from the project where I use it.

**Comment by jjl** [comment]
Awesome! Welcome to the guild! :-D

**Pull request merged**
